#!/bin/zsh

if [[ $# > 0 ]]
then
    CoppiedPath=$PWD/$1
else
    CoppiedPath=$PWD
fi
CoppiedPath="$(python -c "import os,sys; print os.path.realpath(sys.argv[1])" $CoppiedPath)"
echo -n $CoppiedPath | pbcopy
echo $CoppiedPath
