#!/bin/zsh

open -a terminal-notifier --args -sound "Ping" -message $@

# notify "message with spaces" -activate 'com.apple.AddressBook' -subtitle 'Finished' -group 'address-book-sync' -activate 'com.apple.AddressBook'
