#!/bin/zsh

if [[ "$#" = 1 ]]
then
    mkdir ~/.ssh
    if ! (test -e ~/.ssh/id_rsa)
    then
        ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa
    fi

    cat ~/.ssh/id_rsa.pub | ssh "$1" "mkdir -p ~/.ssh && cat >>  ~/.ssh/authorized_keys"
else
    echo "use: <script name> 'user@serverAddress'"
fi
