#!/bin/zsh

if [[ "$#" != 1 || ("$1" != "iPad" && "$1" != "iPhone") ]]
then
    >&2 echo "Use: udid (iPad | iPhone)"
else
    system_profiler SPUSBDataType | sed -n -E -e '/(iPad)/,/Serial/s/ *Serial Number: *(.+)/\1/p'
fi
